.if n.ad l
.nh

.TH debug 1 "2018-11-29" "shellman 0.4.1" "User Commands"

.SH "NAME"
debug \- Shell script debugger

.SH "SYNOPSIS"
\fBdebug\fR [\fB\-tvn\fR] <\fISCRIPT\fR> [\fIARGS\fR]

.SH "DESCRIPTION"
Run a script in path with the -x bash option (and more).
You should set the PS4 variable for better output.

.SH "OPTIONS"
.IP "\fB\-t\fR, \fB\-\-test\fR " 4
Read the script and warn for encountered syntax errors.
Do not actually run the script.

.IP "\fB\-v\fR, \fB\-\-verbose\fR " 4
Run the script with verbose option.

.IP "\fB\-n\fR, \fB\-\-dry\-run\fR " 4
Options test and verbose combined. Validate the syntax
and print the script to stdout.

.IP "\fB\-f\fR, \fB\-\-filter\fR \fIPATTERN\fR" 4
Filter out PATTERN from debug output.

.IP "\fB\-h\fR, \fB\-\-help\fR " 4
Print this help and exit.


.SH "ENVIRONMENT VARIABLES"
.TP
.B PS4
Debugger prompt. This is the prefix that bash prepends to
the current instruction when using -x option.
